function displayInTable(people){
	let output = "";
	for(let i = 0; i < people.length; i++){
		output += "<tr><td>";
		output += person.id;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.firstName;
		output += person.lastName;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.gender:
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.age;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.height;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.weight;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.eyeColor;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.occupation;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.parents;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.currentSpouse;
		output += "</tr></td>";
		output += "<tr><td>";
		output += person.children;
		output += "</tr></td>";
	}
}